### ISSUE TITLE
PermissionsGroups do not have a JSON enumeration

### ISSUE THREAD

**Issue by Nix-Starlight** [CoagulateSL/GPHUD#127]
![image](https://user-images.githubusercontent.com/95241936/161181334-7df3ea4a-46db-4ecd-93d7-32e2a1b5c87b.png)

[19:07] GPHUD: Sorry, an internal error occurred.

**Comment by iprice** [comment]
Relevant exception

net.coagulate.Core.Exceptions.System.SystemImplementationException - Unhandled ENUM TYPE in getJSONTemplate():PERMISSIONSGROUP
 at net.coagulate.GPHUD.Modules.Command.getJSONTemplate(Command.java:290)
 at net.coagulate.GPHUD.Modules.Modules.getJSONTemplate(Modules.java:228)
 at net.coagulate.GPHUD.Modules.Modules.getJSONTemplateResponse(Modules.java:233)
 at net.coagulate.GPHUD.Modules.Menus.MenuCommand.execute(MenuCommand.java:110)
 at net.coagulate.GPHUD.Modules.Command.run(Command.java:494)
 at net.coagulate.GPHUD.Modules.Command.run(Command.java:141)
 at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:324)
 at net.coagulate.GPHUD.Interfaces.System.Interface.execute(Interface.java:305)
 at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:121)
 at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:50)
 at net.coagulate.Core.HTTP.URLMapper._handle(URLMapper.java:106)
 at net.coagulate.Core.HTTP.URLMapper.handle(URLMapper.java:57)
 at org.apache.http.protocol.HttpService.doService(HttpService.java:437)
 at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:342)
 at org.apache.http.impl.bootstrap.Worker.run(Worker.java:66)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.lang.Thread.run(Thread.java:833)
