### ISSUE TITLE
Health.healthinitial unsettable by code?

### ISSUE THREAD

**Issue by justcfx2u** [CoagulateSL/GPHUD#31]
**Describe the bug**
Not sure if bug, but got error message `Sorry, an internal error occurred.` so going to go that route.

**To Reproduce**
```Integer _ = gsSetCharacterKVs(CALLER, ["Health.healthinitial", "1"]);```

**Expected behavior**
Calling `gsSetCharacterKVs(CALLER, ["Health.healthinitial", "1"])` should set the initial health for that specific character instead of yielding an error. (Note: Tested with "1" and "60" for 'integer' part.)

**Additional context**
Setting Health.health works fine:
```Integer _ = gsSetCharacterKVs(CALLER, ["Health.health", "1"]);```

**Comment by iprice** [comment]
It's called "Health.InitialHealth" not what you wrote here.

That said, it would be nice if it gave a better error message for sure.

**Comment by iprice** [comment]
Relevant exception - miscategorised as system error but is user error.

Version: GPHUD | 3.19.5 | 2021-12-06 18:43 | 8dd17e7
net.coagulate.Core.Exceptions.System.SystemImplementationException - Invalid KV healthinitial in module Health
 at net.coagulate.GPHUD.Modules.ModuleAnnotation.getKVDefinition(ModuleAnnotation.java:114)
 at net.coagulate.GPHUD.Modules.Modules.getKVDefinitionNullable(Modules.java:363)
 at net.coagulate.GPHUD.Modules.Modules.getKVDefinition(Modules.java:349)
 at net.coagulate.GPHUD.Modules.Scripting.Language.Functions.KV.gsSetCharacterKVs(KV.java:79)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:566)
 at net.coagulate.GPHUD.Modules.Scripting.Language.ByteCode.BCInvoke.invoke(BCInvoke.java:93)
 at net.coagulate.GPHUD.Modules.Scripting.Language.ByteCode.BCInvoke.execute(BCInvoke.java:79)
 at net.coagulate.GPHUD.Modules.Scripting.Language.GSVM.executeloop(GSVM.java:447)
 at net.coagulate.GPHUD.Modules.Scripting.Language.GSVM.execute(GSVM.java:173)
 at net.coagulate.GPHUD.Modules.Scripting.ScriptingCommand.execute(ScriptingCommand.java:103)
 at net.coagulate.GPHUD.Modules.Command.run(Command.java:494)
 at net.coagulate.GPHUD.Modules.Command.run(Command.java:141)
 at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:310)
 at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:237)
 at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:318)
 at net.coagulate.GPHUD.Interfaces.System.Interface.execute(Interface.java:305)
 at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:121)
 at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:50)
 at net.coagulate.Core.HTTP.URLMapper._handle(URLMapper.java:106)
 at net.coagulate.Core.HTTP.URLMapper.handle(URLMapper.java:57)
 at org.apache.http.protocol.HttpService.doService(HttpService.java:437)
 at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:342)
 at org.apache.http.impl.bootstrap.Worker.run(Worker.java:66)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.lang.Thread.run(Thread.java:829)
net.coagulate.GPHUD.Modules.Scripting.Language.GSInternalError - VM exception: net.coagulate.Core.Exceptions.System.SystemImplementationException: Invalid KV healthinitial in module Health at t row 1, column 13, PC=95, OP=12 (Invoke)
 at net.coagulate.GPHUD.Modules.Scripting.Language.GSVM.executeloop(GSVM.java:452)
 at net.coagulate.GPHUD.Modules.Scripting.Language.GSVM.execute(GSVM.java:173)
 at net.coagulate.GPHUD.Modules.Scripting.ScriptingCommand.execute(ScriptingCommand.java:103)
 at net.coagulate.GPHUD.Modules.Command.run(Command.java:494)
 at net.coagulate.GPHUD.Modules.Command.run(Command.java:141)
 at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:310)
 at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:237)
 at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:318)
 at net.coagulate.GPHUD.Interfaces.System.Interface.execute(Interface.java:305)
 at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:121)
 at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:50)
 at net.coagulate.Core.HTTP.URLMapper._handle(URLMapper.java:106)
 at net.coagulate.Core.HTTP.URLMapper.handle(URLMapper.java:57)
 at org.apache.http.protocol.HttpService.doService(HttpService.java:437)
 at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:342)
 at org.apache.http.impl.bootstrap.Worker.run(Worker.java:66)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.lang.Thread.run(Thread.java:829)

**Comment by justcfx2u** [comment]
I'll test it later, but seems entirely reasonable. Thanks!
