### ISSUE TITLE
Health module returns system error if queried for an invalid KV

### ISSUE THREAD

**Issue by iprice** [CoagulateSL/GPHUD#36]
See #31

**Comment by iprice** [comment]
net.coagulate.Core.Exceptions.System.SystemImplementationException - Invalid KV healthinitial in module Health
at net.coagulate.GPHUD.Modules.ModuleAnnotation.getKVDefinition(ModuleAnnotation.java:114)
at net.coagulate.GPHUD.Modules.Modules.getKVDefinitionNullable(Modules.java:363)
at net.coagulate.GPHUD.Modules.Modules.getKVDefinition(Modules.java:349)
at net.coagulate.GPHUD.Modules.Scripting.Language.Functions.KV.gsSetCharacterKVs(KV.java:79)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at net.coagulate.GPHUD.Modules.Scripting.Language.ByteCode.BCInvoke.invoke(BCInvoke.java:93)
at net.coagulate.GPHUD.Modules.Scripting.Language.ByteCode.BCInvoke.execute(BCInvoke.java:79)
at net.coagulate.GPHUD.Modules.Scripting.Language.GSVM.executeloop(GSVM.java:447)
at net.coagulate.GPHUD.Modules.Scripting.Language.GSVM.execute(GSVM.java:173)
at net.coagulate.GPHUD.Modules.Scripting.ScriptingCommand.execute(ScriptingCommand.java:103)
at net.coagulate.GPHUD.Modules.Command.run(Command.java:494)
at net.coagulate.GPHUD.Modules.Command.run(Command.java:141)
at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:310)
at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:237)
at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:318)
at net.coagulate.GPHUD.Interfaces.System.Interface.execute(Interface.java:305)
at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:121)
at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:50)
at net.coagulate.Core.HTTP.URLMapper._handle(URLMapper.java:106)
at net.coagulate.Core.HTTP.URLMapper.handle(URLMapper.java:57)
at org.apache.http.protocol.HttpService.doService(HttpService.java:437)
at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:342)
at org.apache.http.impl.bootstrap.Worker.run(Worker.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:829)
net.coagulate.GPHUD.Modules.Scripting.Language.GSInternalError - VM exception: net.coagulate.Core.Exceptions.System.SystemImplementationException: Invalid KV healthinitial in module Health at t row 1, column 13, PC=95, OP=12 (Invoke)
at net.coagulate.GPHUD.Modules.Scripting.Language.GSVM.executeloop(GSVM.java:452)
at net.coagulate.GPHUD.Modules.Scripting.Language.GSVM.execute(GSVM.java:173)
at net.coagulate.GPHUD.Modules.Scripting.ScriptingCommand.execute(ScriptingCommand.java:103)
at net.coagulate.GPHUD.Modules.Command.run(Command.java:494)
at net.coagulate.GPHUD.Modules.Command.run(Command.java:141)
at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:310)
at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:237)
at net.coagulate.GPHUD.Modules.Modules.run(Modules.java:318)
at net.coagulate.GPHUD.Interfaces.System.Interface.execute(Interface.java:305)
at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:121)
at net.coagulate.GPHUD.Interfaces.System.Interface.executePage(Interface.java:50)
at net.coagulate.Core.HTTP.URLMapper._handle(URLMapper.java:106)
at net.coagulate.Core.HTTP.URLMapper.handle(URLMapper.java:57)
at org.apache.http.protocol.HttpService.doService(HttpService.java:437)
at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:342)
at org.apache.http.impl.bootstrap.Worker.run(Worker.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:829)
